In [9]:
import numpy as np

a = np.arange(2*3*2).reshape(2,3,2)
print(a)
b = a[:,np.newaxis,:]
print(b.shape)


[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
(2, 1, 3, 2)


In [13]:
#a = np.arange(3*4*5*6).reshape((3,4,5,6))
b = np.arange(12)[:3:-2]
#c = b.reshape((5,4,6,3))
print(b)
#np.dot(a, b)[2,3,2,1,2,2]
#499128
#sum(a[2,3,2,:] * b[1,2,:,2])
#499128

[11  9  7  5]


In [14]:
import numpy as np
a = np.array([[1,2],[3,4]])
print(a)
b = a[0:1,1]
b[0] = 5
print(a)

a = np.array([[1,2],[3,4]])
print(a)
b = a[1,1]
b = 5
print(a)

a = np.array([[1,2],[3,4]])
print(a)
b = a[[0,1],[0,1]]
print(b.shape,b)
b[0] = 5
print(a)

c = [[1,2],[3,4]]
print(c)
d = c[0:1]

d[0] = 5
print(c)

[[1 2]
 [3 4]]
[[1 5]
 [3 4]]
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
(2,) [1 4]
[[1 2]
 [3 4]]
[[1, 2], [3, 4]]
[[1, 2], [3, 4]]


In [15]:
a = range(5)
print(type(a))

<class 'range'>


In [16]:
t = (1,2,3)
print(type(t))

<class 'tuple'>


In [17]:
a = [1,2]*3
print(a)

[1, 2, 1, 2, 1, 2]


In [19]:
a = [1]*3
print(a)

[1, 1, 1]


In [20]:
a = [[1,2],[3,4]]*3
print(a)

[[1, 2], [3, 4], [1, 2], [3, 4], [1, 2], [3, 4]]


In [21]:
import numpy as np
a = np.array(['a', 'b', 'b', 'c', 'a'])
u, indices = np.unique(a, return_index=True)
print(u, indices)

['a' 'b' 'c'] [0 1 3]


In [22]:
import numpy as np
a = np.array(['a', 'b', 'b', 'c', 'a'])
u, indices = np.unique(a, return_inverse=True)
print(u, indices)


['a' 'b' 'c'] [0 1 1 2 0]


In [23]:
import numpy as np
a = np.array(['a', 'b', 'b', 'c', 'a'])
u, indices = np.unique(a, return_counts=True)
print(u, indices)


['a' 'b' 'c'] [2 2 1]


In [24]:
import numpy as np
a = np.array(['a', 'b', 'b', 'c', 'a'])
u, indices, b = np.unique(a, return_counts=True, return_inverse=True)
print(u, indices, b)

['a' 'b' 'c'] [0 1 1 2 0] [2 2 1]


In [6]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = a[0:2,0:2]
print(b)
c = a[range(2), range(2)]
print(c)
d = a[0:2, [1,1]]
print(d)
#c = a[]

[[1 2]
 [4 5]]
[1 5]
[[2 2]
 [5 5]]
